baseURL = "https://xqqy.netlify.app/"
languageCode = "zh-cn"
title = "喵喵喵的小破站"
theme ="ananke"
hasCJKLanguage = true

[params]
  author = "xqqy"
  SEOTitle = "喵喵喵的小破站"
  description = "记录大学的事件，曾经是一个班级的网站"
  slogan = "喵呜～"
  dateFormat = "1970年1月1日"
  title_404 = "你来到了没有猫咪的荒原 :("
  showtoc = false
  nextpost = false
  background_color_class = "bg-gray"

  featured_tags=true
  
  friends = true
  bookmarks = true
  
[Menus]
  main = [
      #{Name = "周安排", URL = "/周安排/"},
      {Name = "各种资料", URL = "/各种资料/"},
      {Name = "办事指南", URL = "/办事指南/"},
      #{Name = "卫星观测", URL = "/卫星观测/"},
      {Name = "出校申请", URL = "/出校申请/"},
      {Name = "答案比对", URL = "/ans-check/"},
  ]
[markup]
  defaultMarkdownHandler = "goldmark"
