baseURL = "https://xqqy.gitee.io/"
languageCode = "zh-cn"
title = "注会191喵呜～"
theme ="cleanwhite"
hasCJKLanguage = true

[params]
  author = "xqqy"
  SEOTitle = "注会191班级网站"
  description = "通知、资料还有卫星观测"
  slogan = "喵呜～"
  dateFormat = "1970年1月1日"
  title_404 = "你来到了没有猫咪的荒原 :("
  showtoc = false
  nextpost = false

  featured_tags=true
  
  friends = true
  bookmarks = true
  [[params.bookmark_link]]
  title =  "周安排"
  href =  "周安排/"
  [[params.bookmark_link]]
  title =  "各种资料"
  href =  "各种资料/"
  [[params.bookmark_link]]
  title =  "办事指南"
  href =  "办事指南/"
  #[[params.bookmark_link]]
  #title =  "卫星观测"
  #href =  "卫星观测/"
  [[params.bookmark_link]]
  title =  "抽签程序"
  href =  "抽签程序/"
  
  [[params.addtional_menus]]
  title =  "周安排"
  href =  "周安排/"
  [[params.addtional_menus]]
  title =  "各种资料"
  href =  "各种资料/"
  [[params.addtional_menus]]
  title =  "办事指南"
  href =  "办事指南/"
  #[[params.addtional_menus]]
  #title =  "卫星观测"
  #href =  "卫星观测/"
  [[params.addtional_menus]]
  title =  "抽签程序"
  href =  "抽签程序/"
  
  [[params.friend_link]]
  title = "北京工商大学官网"
  href =  "http://www.btbu.edu.cn"
  [[params.friend_link]]
  title = "北京工商大学教务处"
  href =  "http://jwc.btbu.edu.cn"
  [[params.friend_link]]
  title = "北京工商大学商学院"
  href =  "http://sxy.btbu.edu.cn"
  [[params.friend_link]]
  title = "北京工商大学体育与艺术教学部"
  href =  "http://sports.btbu.edu.cn"
  
[Menus]
  main = [
      {Name = "周安排", URL = "/周安排/"},
      {Name = "各种资料", URL = "/各种资料/"},
      {Name = "办事指南", URL = "/办事指南/"},
      #{Name = "卫星观测", URL = "/卫星观测/"},
  ]
[markup]
  defaultMarkdownHandler = "blackfriday"
